export default {
	body: { marginTop: '130px' },
	chatIcon: {
		position: 'fixed',
		right: 20,
		bottom: 20,
		fontSize: '30pt',
	},
	botSpeak: {
		float: 'left',
		borderRadius: '10px',
		borderBottomLeftRadius: '2px',
		backgroundColor: 'hotpink',
		padding: '5px 10px',
		color: 'white',
		marginBottom: '10px',
	},
	userSpeak: {
		float: 'right',
		borderRadius: '10px',
		borderBottomRightRadius: '2px',
		backgroundColor: '#1890ff',
		padding: '5px 10px',
		color: 'white',
		marginBottom: '10px',
	},
	logo: {
		position: 'fixed',
		left: 15,
		top: 5,
	},
	themeSwitch: { position: 'fixed', top: 25, right: 20 },
	navRight: { float: 'right' },
	chatBoxTitle: { position: 'relative', top: 10, left: 5 },
	chatBox: {
		height: '500px',
		maxWidth: '80%',
		width: '350px',
		position: 'fixed',
		bottom: 50,
		right: 60,
		boxShadow: '1px 1px 10px 2px #F0F0F0',
		borderRadius: '10px',
	},
	icon: { fontSize: '14pt', color: 'hotpink', position: 'relative', top: 5 },
	messageSend: { width: '330px', maxWidth: '100%' },
	chatDiv: { height: '340px' },
	alert: {
		position: 'fixed',
		top: 74,
		right: 0,
		left: 0,
		width: '100%',
		color: 'white',
		padding: '5px',
		backgroundColor: '#c90711',
		border: '1px solid #c90711',
		opacity: '0.75',
		textAlign: 'center',
	},
	alertIcon: {
		marginRight: '10px',
	},
};
